tests/common/util: Use is_none_or instead of map_or
Following clippy advice:
error: this `map_or` can be simplified
     --> tests\common\util.rs:411:9
      |
  411 |         self.exit_status.map_or(true, |e| e.success())
      |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use is_none_or instead: `self.exit_status.is_none_or(|e| e.success())`