stdbuf: fix a publish issue
failed with:
error: all dependencies must have a version specified when publishing.
dependency `uu_stdbuf_libstdbuf` does not specify a version
Note: The published dependency will use the version from crates.io,
the `path` specification will be removed from the dependency declaration.